### PR TITLE
display long words properly - fixes #8

### LINKED ISSUE #8: Break up words longer than the max width
So this won't happen:

```
yosay 'iloveunicornsiloveunicornsiloveunicornsiloveunicornsiloveunicornsiloveunicorns'
    _-----_
    |       |    .--------------------------.
    |--(o)--|    | iloveunicornsiloveunicornsiloveunicornsiloveunicornsiloveunicornsiloveunicorns |
   `---------´   '--------------------------'
    ( _´U`_ )    
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 
```

### PR DESCRIPTION
**Pull request by danilosampaio**
Wrap words longer than the max width, displaying the message without breaking the frame. (fix #8)

Before:

image

After:

image

The main change is the word wrap dependency. Initially, i made a module for my needs([greedy-wrap](https://github.com/danilosampaio/greedy-wrap)), but after running some tests, it fits well into yosay.

Additionally, it fixes duplicated linebreaks (https://github.com/jonschlinkert/word-wrap/issues/10).

Obviously, greedy-wrap ins't as mature as word-wrap. If you are interested, i'll happy to help. :smile:

### CODE REVIEW

**Comment by sindresorhus** [comment]
Curious, how does it compare to [`wrap-ansi`](https://github.com/chalk/wrap-ansi) which is already battle-tested?

**Comment by danilosampaio** [comment]
@sindresorhus `wrap-ansi` gets the same result as `greedy-wrap`: it fixes #8 and the duplicated linebreaks (jonschlinkert/word-wrap#10). It's up to you.

**Comment by eddiemonge** [comment]
I'd prefer to go with wrap-asi

**Comment by sindresorhus** [comment]
Then I'd go with `wrap-ansi` since it's already used by `yargs`, `vorpal`, etc.

**Comment by danilosampaio** [comment]
Ok, so are you interested in equivalent PR, with wrap-ansi?

**Comment by sindresorhus** [comment]
@danilosampaio Just change the dependency and update this PR.

**Comment by addyosmani** [comment]
:+1: for just using `wrap-ansi`. If you could update the PR rather than creating a new one that would be ace.

**Comment by danilosampaio** [comment]
Done. :+1:

**Comment by sindresorhus** [comment]
Thanks @danilosampaio :)

**Pull request merged**
