### PR TITLE
Fix new line bug

### PR DESCRIPTION
**Pull request by aharris88**
Fixes issue #9

### CODE REVIEW

**Comment by mischah** [comment]
Thanks man :kissing_heart:

**Comment by SBoudrias** [comment]
Can you add a unit test?

**Comment by aharris88** [comment]
Yeah, I'll do that.

**Comment by aharris88** [comment]
How do I convert this output to the format used in the unit tests?


     _-----_
    |       |    .--------------------------.
    |--(o)--|    |            hi            |
   `---------´   |                          |
    ( _´U`_ )    |            ok            |
    /___A___\    '--------------------------'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

**Comment by sindresorhus** [comment]
Gotta love implicit coercion :p

You can just redirect the terminal output to a file: `yosay somethin > file.txt`

Thanks for fixing @aharris88 :)

// @stephenplusplus

**Comment by aharris88** [comment]
Thanks @sindresorhus, that was close to what I needed. It didn't do the colors, the \n characters, and it didn't escape the single quotes, but it got me on the right track.

I seem to be having trouble with this. I would expect this test to pass, but it's not. I also can't get mocha to give me a diff between the expected and the actual, so I'm not sure what's wrong

    it('should handle new lines', function() {
      var expected = '\n     _-----_\n    |       |    .--------------------------.\n    |\u001b[31m--(o)--\u001b[39m|    \u001b[0m|\u001b[0m            \u001b[0mhi\u001b[0m            \u001b[0m|\u001b[0m\n   `---------´   \u001b[0m|                          |\n    \u001b[33m(\u001b[39m _\u001b[33m´U`\u001b[39m_ \u001b[33m)    \u001b[0m|\u001b[0m            \u001b[0mok\u001b[0m            \u001b[0m|\u001b[0m\n    /___A___\\    \u001b[0m\'--------------------------\'\n     \u001b[33m|  ~  |\u001b[39m     \n   __\u001b[33m\'.___.\'\u001b[39m__   \n ´   \u001b[31m`  |\u001b[39m° \u001b[31m´ Y\u001b[39m ` \n';
      console.log(expected);
      console.log(yosay('hi\nok'));
      assert.equal(yosay('hi\nok'), expected);
    });

**Comment by stephenplusplus** [comment]
@aharris88 thanks indeed for doing this!

I was able to get the test working with this:

```js
it('should handle new lines', function () {
      var expected = '\n     _-----_\n    |       |    .--------------------------.\n    |\u001b[31m--(o)--\u001b[39m|    \u001b[0m|\u001b[0m            \u001b[0mhi\u001b[0m            \u001b[0m|\u001b[0m\n   `---------´   \u001b[0m|\u001b[0m             \u001b[0m\u001b[0m             \u001b[0m|\u001b[0m\n    \u001b[33m(\u001b[39m _\u001b[33m´U`\u001b[39m_ \u001b[33m)\u001b[39m    \u001b[0m|\u001b[0m            \u001b[0mok\u001b[0m            \u001b[0m|\u001b[0m\n    /___A___\\    \u001b[0m\'--------------------------\'\n     \u001b[33m|  ~  |\u001b[39m     \n   __\u001b[33m\'.___.\'\u001b[39m__   \n ´   \u001b[31m`  |\u001b[39m° \u001b[31m´ Y\u001b[39m ` \n';
      assert.equal(yosay('hi\nok'), expected);
    });
```

My secret was: `require('fs').writeFileSync('./blah.txt', JSON.stringify(yosay('hi\nok')))`

Here's the diff between yours and the new one:

```diff
-var expected = '\n     _-----_\n    |       |    .--------------------------.\n    |\u001b[31m--(o)--\u001b[39m|    \u001b[0m|\u001b[0m            \u001b[0mhi\u001b[0m            \u001b[0m|\u001b[0m\n   `---------´   \u001b[0m|                          |\n    \u001b[33m(\u001b[39m _\u001b[33m´U`\u001b[39m_ \u001b[33m)    \u001b[0m|\u001b[0m            \u001b[0mok\u001b[0m            \u001b[0m|\u001b[0m\n    /___A___\\    \u001b[0m\'--------------------------\'\n     \u001b[33m|  ~  |\u001b[39m     \n   __\u001b[33m\'.___.\'\u001b[39m__   \n ´   \u001b[31m`  |\u001b[39m° \u001b[31m´ Y\u001b[39m ` \n';
+var expected = '\n     _-----_\n    |       |    .--------------------------.\n    |\u001b[31m--(o)--\u001b[39m|    \u001b[0m|\u001b[0m            \u001b[0mhi\u001b[0m            \u001b[0m|\u001b[0m\n   `---------´   \u001b[0m|\u001b[0m             \u001b[0m\u001b[0m             \u001b[0m|\u001b[0m\n    \u001b[33m(\u001b[39m _\u001b[33m´U`\u001b[39m_ \u001b[33m)\u001b[39m    \u001b[0m|\u001b[0m            \u001b[0mok\u001b[0m            \u001b[0m|\u001b[0m\n    /___A___\\    \u001b[0m\'--------------------------\'\n     \u001b[33m|  ~  |\u001b[39m     \n   __\u001b[33m\'.___.\'\u001b[39m__   \n ´   \u001b[31m`  |\u001b[39m° \u001b[31m´ Y\u001b[39m ` \n';
```

**Comment by aharris88** [comment]
I've got it to pass the second test, but not the other 2. It always adds an empty line. 

`yosay hi\nok` should look this this:

         _-----_
        |       |    .--------------------------.
        |--(o)--|    |            hi            |
       `---------´   |            ok            |
        ( _´U`_ )    '--------------------------'
        /___A___\
         |  ~  |
       __'.___.'__
     ´   `  |° ´ Y `

And `yosay 'hi\n\n\nok'` should look like this:

         _-----_
        |       |    .--------------------------.
        |--(o)--|    |            hi            |
       `---------´   |                          |
        ( _´U`_ )    |                          |
        /___A___\    |            ok            |
         |  ~  |     '--------------------------'
       __'.___.'__
     ´   `  |° ´ Y `

Instead it always looks like this:

         _-----_
        |       |    .--------------------------.
        |--(o)--|    |            hi            |
       `---------´   |                          |
        ( _´U`_ )    |            ok            |
        /___A___\    '--------------------------'
         |  ~  |
       __'.___.'__
     ´   `  |° ´ Y `

    it('should handle a new line', function () {
      var expected = '\n     _-----_\n    |       |    .--------------------------.\n    |\u001b[31m--(o)--\u001b[39m|    \u001b[0m|\u001b[0m            \u001b[0mhi\u001b[0m            \u001b[0m|\u001b[0m\n   `---------´   \u001b[0m|\u001b[0m            \u001b[0mok\u001b[0m            \u001b[0m|\u001b[0m\n    \u001b[33m(\u001b[39m _\u001b[33m´U`\u001b[39m_ \u001b[33m)\u001b[39m    \u001b[0m\'--------------------------\'\n    /___A___\\    \n     \u001b[33m|  ~  |\u001b[39m     \n   __\u001b[33m\'.___.\'\u001b[39m__   \n ´   \u001b[31m`  |\u001b[39m° \u001b[31m´ Y\u001b[39m ` \n';
      assert.equal(yosay('hi\nok'), expected);
    });
  
    it('should handle 2 new lines', function () {
      var expected = '\n     _-----_\n    |       |    .--------------------------.\n    |\u001b[31m--(o)--\u001b[39m|    \u001b[0m|\u001b[0m            \u001b[0mhi\u001b[0m            \u001b[0m|\u001b[0m\n   `---------´   \u001b[0m|\u001b[0m             \u001b[0m\u001b[0m             \u001b[0m|\u001b[0m\n    \u001b[33m(\u001b[39m _\u001b[33m´U`\u001b[39m_ \u001b[33m)\u001b[39m    \u001b[0m|\u001b[0m            \u001b[0mok\u001b[0m            \u001b[0m|\u001b[0m\n    /___A___\\    \u001b[0m\'--------------------------\'\n     \u001b[33m|  ~  |\u001b[39m     \n   __\u001b[33m\'.___.\'\u001b[39m__   \n ´   \u001b[31m`  |\u001b[39m° \u001b[31m´ Y\u001b[39m ` \n';
      assert.equal(yosay('hi\n\nok'), expected);
    });
  
    it('should handle multiple new lines', function () {
      var expected = '\n     _-----_\n    |       |    .--------------------------.\n    |\u001b[31m--(o)--\u001b[39m|    \u001b[0m|\u001b[0m            \u001b[0mhi\u001b[0m            \u001b[0m|\u001b[0m\n   `---------´   \u001b[0m|\u001b[0m             \u001b[0m\u001b[0m             \u001b[0m|\u001b[0m\n    \u001b[33m(\u001b[39m _\u001b[33m´U`\u001b[39m_ \u001b[33m)\u001b[39m    \u001b[0m|\u001b[0m             \u001b[0m\u001b[0m             \u001b[0m|\u001b[0m\n    /___A___\\    \u001b[0m|\u001b[0m            \u001b[0mok\u001b[0m            \u001b[0m|\u001b[0m\n     \u001b[33m|  ~  |\u001b[39m     \u001b[0m\'--------------------------\'\n   __\u001b[33m\'.___.\'\u001b[39m__   \n ´   \u001b[31m`  |\u001b[39m° \u001b[31m´ Y\u001b[39m ` \n';
      assert.equal(yosay('hi\n\n\nok'), expected);
    });

**Comment by sindresorhus** [comment]
@stephenplusplus thoughts?

**Comment by stephenplusplus** [comment]
When it comes to fixing the bug, I admitted defeat a long time ago. I tried to make it easier to test however: #14.

Keep in mind we are running the user's input to yosay through a `wrap` module, which returns the same string with new-lines where it thinks they should be, given the maximum length for a line we specify.

**Comment by sindresorhus** [comment]
@aharris88 Would you mind rebasing and using the new test template?

**Comment by arthurvr** [comment]
ping @aharris88

**Comment by aharris88** [comment]
Like I mentioned above [I wrote 3 tests](https://github.com/aharris88/yosay/commit/994980f7c20fd332dd646516258a91c57572f5c5) that should pass if this bug is to get fixed.

But [I was only able to make the second test pass](https://github.com/aharris88/yosay/commit/796563626f7abe9bb953126d904fb29dd2465334). And I haven't worked on it since.

**Comment by arthurvr** [comment]
It looks like some unrelated commits got into this PR. Besides from that, this needs a rebase.

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/yeoman/yosay/pull/20

**Pull request closed without merging**
